### ISSUE TITLE
[1.10.2] control panel crash server

### ISSUE THREAD

**Issue by ghost** [malte0811/IndustrialWires#11]
https://pastebin.com/yhuAnFC8

https://pastebin.com/x8FvadwD

**Comment by malte0811** [comment]
Looks like I fixed this in 1.12 and forgot to backport it. I will release a fix for 1.10 and 1.11 either later today or tomorrow (depends on how many other fixes I didn't backport).

**Comment by ghost** [comment]
Great! Thanks a lot.

**Comment by malte0811** [comment]
https://minecraft.curseforge.com/projects/industrial-wires/files/2460121
The 1.11.2 version should be available soon as well.
