### ISSUE TITLE
Can't seem to figure out the Marx Generator?

### ISSUE THREAD

**Issue by Buggy123** [malte0811/IndustrialWires#16]
In ATM3 I decided to try using a Marx Generator for getting coal out of coal ore, since it's the most efficient  method available. However, it doesn't seem to work. I've tried solving for the redstone signal required to refine 3 coal ore (225kJ), the equation I got was (16A+B)=sqrt(X/0.0000008)*(255/250)/1000, where X is the desired per-capacitor joules, A is the white channel strength and B the yellow channel strength. The whole setup is triggered with a pulse to light blue.

I'm not 100% sure how many capacitors there are, since the smallest structure is built with 10 but once finished appears to be five, but neither value seems to result in _any_ coal being outputted. I've tried values close to that, as well as many different random signal strengths to see if anything would work, and I've got nothing. I haven't quite tried _every_ single possible input signal, but that's my next step. To be clear, each time I wait for the top and bottom capacitors to finish charging, and then fire it.

Is the range of input voltage where you'll get any sort of output at all extremely small? Overall the documentation for the generator is pretty scarce, I've read the manual front-to-back several times, but I still can't figure it out. And there's no help to be found online, I've only been able to find a single mention of the IW Marx Generator outside of this repository.

Any sort of clarification here would be very helpful, and I'd strongly recommend expanding the documentation page a bit. Here's a few pictures of my current setup, the chest there is just in case it ejects to a nearby inventory instead of dropping the items in the world: https://imgur.com/a/eyI3E

**Comment by malte0811** [comment]
Your formula is correct, the signals should be 15 and 2 for 225 kJ. Each stage is treated as one capacitor (even though it is made from 2). I'll test whether ore processing is broken when I'm back from Uni. The range of energy which gives you output is relatively small and may not be centered perfectly on 225 kJ (10% variation, though I am thinking about removing that in the next release), but you should get some output at 225 kJ.
I'll try to improve the documentation, I've added something to automatically seperate the text into pages so it should be easier to do now. It would be great if you could tell me some details that could do with better documentation.
BTW: the danger distance formulas in the manual are wrong, the hearing damage has a larger range than indicated.

**Comment by malte0811** [comment]
I just tested ore processing, it seems to be working as intended.
 - As I said there is up to a 10% inaccuracy to the energy values in the manual. I tested with both worst-case inaccuracies, you should be getting at least 5 coal/ore.
 - Did you by chance evaluate your formula using Python? / and // changed meaning between Python 2 and 3, your formula is correct in Python 3 (Just made that mistake, my earlier values are from a mobile Python 3 interpreter and therefore correct).
 - Is the Marx generator firing properly? There should be a loud bang and the coal ore should be broken, even if it doesn't produce anything.
 - If you don't get any output with 15 and 2 as the voltage run `/iw getmarx` (if you have OP/cheat permissions). That should print out a number between 0.9 and 1.1, if it doesn't that's the problem.
 - The items will just land on the ground, so the chest isn't necessary.

**Comment by Buggy123** [comment]
It's firing properly, and /iw getmarx reports about 1.06, but still nothing. I've uploaded a video of it in action: https://youtu.be/a4R9ms0rhSI

**Comment by malte0811** [comment]
I fixed this by accident, that's why it worked for me. It is a stupid bug and I can't think of a good temporary workaround. The MG thinks there is more ore than there actually is (13 vs 3 in this case), resulting in a very low energy per ore. Unfortunately this value is only roughly proportional to the amount of ore blocks and changes for different stage counts. I'll try to publish a new build with the fix this weekend.
You said the documentation could be improved. I am not very good at writing documentation on something I have been working on for a long time. What parts of the documentation are confusing or could be improved? I'll try to improve them for the next build if you tell me.
