### ISSUE TITLE
Wires keeps disappearing

### ISSUE THREAD

**Issue by maham** [malte0811/IndustrialWires#19]
My copper and tin wires keeps disappearing. After this the connectors won't accept a new wire until I remove and replace them.
Also I can't create coils by combining uninsulated wires, or combining coils.

Versions:
Minecraft 1.12.2
Forge: 14.23.0.2531
IC2: 2.8.16-ex112
IW: 1.6-22
IE: 0.12-75

**Comment by malte0811** [comment]
I'll look into the crafting issue.
Do normal IE wires disappear as well? What other mods do you have installed?

**Comment by maham** [comment]
I'll have a try with IE wires in a moment and report back.

**Comment by maham** [comment]
I have had some IE wires mounted for a while now and they are still there. I have been far away and in the nether without them disappearing.

**Comment by malte0811** [comment]
The crafting issue is fixed now, I forgot to remove some debug code for the release.
I haven't been able to replicate the other issue at all. What other mods are you using? Is this happening on a server or in singleplayer? Could you get me a log of when this happens (Server log if it's on a server, client log if it's singleplayer)? Ideally all three log files (fml-client/server-latest.log, latest.log and fml-junk-earlystartup), the logging seems to have split up between all of them, no idea why.

**Comment by maham** [comment]
After I added the IE wires to the map the IW wires don't disappear anymore... If it occurs again I'll try to remember to grab a log and create a new issue.
