### ISSUE TITLE
Cabel length not Correct

### ISSUE THREAD

**Issue by kuxii2016** [malte0811/IndustrialWires#2]
The length is not Correct,
Can Add ah Config for the Custom Settings for Lose and Lenght? 2048 for ah Glas Cable is very Low 4096 its better.

**Comment by malte0811** [comment]
Length maybe. The wire loss is the same per block of wire as for the normal IC2 wires, which can't be changed either AFAIK.

**Comment by malte0811** [comment]
I added the config option in 3bd6c142660b89019b559dab5f102e7cc045c152. BTW, coils with the same amount of wire on them stack, but have to be unstacked to use them for linking. So a full stack of glass fiber wire coils contains 131072 blocks of wire, which should be enough for all practical purposes.
