### ISSUE TITLE
[1.12.2] Crash on interacting with control panel

### ISSUE THREAD

**Issue by lukiono** [malte0811/IndustrialWires#20]
Greetings, 

When placing a control panel and interacting with the elements on it it crashes the game after hanging for a few seconds.

MC Version: 1.12.2
Forge Version: 1.12.2 - 14.23.1.2555
FoamFix 0.8.1 Anarchy ~~and Optifine HD U C7~~ also used

Crash log: https://ybin.me/p/625086201327057a#gYh4Axck2oObUEmHkKJXyMb3irajSZtazP9kYcdb/2w=

Edit:
It's an incompatibility with Unicode Font Extension
https://minecraft.curseforge.com/projects/unicode-font-extension

Kind regards,
Lukas

**Comment by malte0811** [comment]
I'm pretty certain that will crash with the new default missing model (that contains the error message) as well. As a workaround you could try disabling the multithreaded rendering option (the one Direwolf20 did a video on recently). I'll have a look later today, though I'm quite sure it's their fault (but don't go yelling at them yet).

**Comment by lukiono** [comment]
Sorry, checked the dev enviroment for the modpack again. optifine was not installed in this instance. my bad. 

after disabling unicode it works fine.

which multithreading do you refer to?

**Comment by malte0811** [comment]
[This](https://www.youtube.com/watch?v=t-BgOlJ8N4U) is the video I was talking about. To get to the option (From the main menu) click mods, find and select Minecraft Forge, click config, select client settings and set "Force threaded chunk rendering" to false if it isn't already. If it is set to false already, there isn't much that would fix this besides not using control panels with labels or panel meters on them or removing IndustrialWires or Unicode Font Extension.
The same crash happens with the new missing model (as I suspected above), I'll report that to them. A fix for that issue should fix this one as well.
