### ISSUE TITLE
Custom processing via the marx generator

### ISSUE THREAD

**Issue by ghost** [malte0811/IndustrialWires#23]
Do you think you might be able to add custom processing recipe support to the marx generator?

**Comment by malte0811** [comment]
It should have [CraftTweaker support](https://github.com/malte0811/IndustrialWires/blob/MC1.12/src/main/java/malte0811/industrialWires/compat/CTMarxGenerator.java). Is that not working?

**Comment by ghost** [comment]
ah, I missed that :)
  thanks!
