### ISSUE TITLE
Crafting of coils

### ISSUE THREAD

**Issue by lovelyjohn2002** [malte0811/IndustrialWires#24]
Cant craft any coils. Mods on my server are TechReborn and IndustrialCraft2, TechReborn wires are fobidden because of IC2 Wires, and the recipe for coil doesn´t work. Any fix is coming?

**Comment by malte0811** [comment]
Take a look at the [contributing guidelines](https://github.com/malte0811/IndustrialWires/blob/MC1.12/CONTRIBUTING.md). The most important bits that are missing here are the MC version and a full mod list (or is it just IC2 and TR?). Can you try whether TR wires work for crafting coils (maybe in a singleplayer world)?

**Comment by lovelyjohn2002** [comment]
Is there anyway to post mod list ? :D BTW, Modpack is on Technic Launcher, and it´s called ZidanWolf19. A tried both, single and multiplayer. 

industrialcraft-2-2.8.16-ex112 -- IC2 version
TechReborn-1.12.2-2.12.1.446-universal -- TechReborn version
Minecraft 1.12.2 Forge 
14.23.1.2590 Forge
Industrial-Wires-Mod-1.12.jar -- IWM version

**Comment by malte0811** [comment]
You are using a severely outdated version of IW (in addition to one from an unofficial source). I fixed this bug in afccf9b6776769dc22bcbcd4cce133e24e3ae88e (about 2 months ago). The only official source of this mod is https://minecraft.curseforge.com/projects/industrial-wires, and that is also the only place where you are guaranteed to get the latest version.
