### ISSUE TITLE
Redstone controller not connecting

### ISSUE THREAD

**Issue by Raven2911b** [malte0811/IndustrialWires#25]
I just did some testing. The redstone controller will not allow any restone wire to connect to it when the Immersive Engineering version is 0.12.77 and above.  I ran a test with only IE and IW. At IE 0.12.76, I can connect the controller with no problems.  When I run it with 0.12.76, connect the redstone wire to it, shut down minecraft and restart with IE 0.12.77 (up to 0.12.80), the connector holds and the controller works fine.  It is a bit of work switching versions all the time for a work around.  

I did read that at IE 0.12.77 changelog stated, "Fixed Nullpointer on Redstone Probes (BluSunrize)".
Would that have anyting to do with it, and is there a fix for it?

Thanks

PS.  There are no other mods installed... only Immersive Engineering and Indstrial Wires (ver 1.6-24)
Minecraft 1.12.2
Forge 14.23.2.2611

**Comment by malte0811** [comment]
Why are you using IW build 24? This should be fixed in IW build 25, which I released pretty much at the same time as IE 77 was released.

**Comment by Raven2911b** [comment]
Well, dummy me.... how did I miss that? You're right, it works just fine. Thanks Malte
