### ISSUE TITLE
IT DOESNT FUCKING WORK

### ISSUE THREAD

**Issue by nickflik0934** [malte0811/IndustrialWires#26]

**Comment by nickflik0934** [comment]
so, i made the structure, and i do not know how to make it into a multi-structure.

**Comment by nickflik0934** [comment]
what the hell do you hit with your hammer, i have hit every part of the structure

**Comment by malte0811** [comment]
You form it by hitting one of the bottom capacitors from the side (I don't remember which one right now). That's assuming you're trying to build a Marx generator, which you never actually said. Also please try to limit swearing to the content of your post (keeping it out of the title), if you absolutely have to swear.

**Comment by nickflik0934** [comment]
alright, got it working. just got really frustrated after so much time spent to nothing.

**Comment by nickflik0934** [comment]
thx
