### ISSUE TITLE
Video shows only one redstone wire...but the panel shown uses a lot more then just one

### ISSUE THREAD

**Issue by GazbonicAcid** [malte0811/IndustrialWires#27]
[Video shows only one redstone wire...but the panel shown uses a lot more then just one](https://minecraft.curseforge.com/projects/industrial-wires?comment=64).
Because of the way the connection system works,
you **_have to_** use a separate redstone connector from this mod for _every single item_ on the panel.
So is this difference a false representation hiding how many connectors the panel in the video uses?
Or is it that it's a dev/non-1.12.2 build not publicly available for 1.12.2 on curse?

Edit:
The panel components have to have a set connector they run through.
And if you had all of those components on the same connector,
it wouldn't have worked the way you showed it.

Edit2:
Does the [example video](https://www.youtube.com/watch?v=hV0cN20vCMY) use features not available in 1.12.2 builds on curseforge? or is it working with a binary flag system (1, 2, 4, 8, 16)?

Edit3:
In [this video](https://www.youtube.com/watch?v=W-3X5do7TXI) I found out it does bundled channels.

And there's no mention of this fact in the manual.

**Comment by GazbonicAcid** [comment]
How do I even take advantage of the bundled inputs/outputs? \(will look in manual and ninja-snip this if/when I see it there\)

**Comment by malte0811** [comment]
It isn't explicitely mentioned in the manual entry on IE redstone wires, but all of them have 16 analog channels/frequencies. So you need one wire for every 16 signals (the maximum I have needed so far was 2 wires, now that breaker switches work for RS wires I'd need just one).
