### ISSUE TITLE
This title will inevitably be horrible.

### ISSUE THREAD

**Issue by PegasusEpsilon** [malte0811/IndustrialWires#29]
Playing on a straight Forge server, no sponge or any of that nonsense...

I have a triple water wheel hooked to a converter (rotational to kinetic) hooked to a kinetic generator hooked to a copper wire connector, going through two copper wire relays, finally to another copper wire connector, and then an MFE. When the MFE is not full, the EU-Reader says the copper wire connector connected to the kinetic generator is taking in 18.75EU/t, and the copper wire connector connected to the MFE is putting out 18.75EU/t. This I take to be intended operation of the mod, and it makes me happy.

Tin connectors explode, despite the kinetic generator putting out only 18.75EU/t, but I accept that it's probably not being fed as much KE as it can take, and just chalk that up to quirks.

However...

I have a full CESU with its output hooked to a copper wire connector, running through a pair of copper wire relays, and then through a block with a copper wire connector on each side (whacked with the hammer so the EU goes through, and HWYLA says it's now a "Feedthrough Insulator") and then the other end of the feedthrough insulator is hooked to an MFE. This is where things go weird. It seems the length of the wire between the CESU and the feedthrough insulator is limiting the power the copper wire connector connected to the output of the CESU will actually accept. The CESU should be able to put out 128EU/t, it is *full*, and it's only putting out 58.6EU/t, unless I move it closer to the feedthrough insulator, in which case (when moved 8 blocks closer) it puts out 61.65 EU/t.

Is this...intended behavior? Does putting a feedthrough insulator in the way somehow alter the power network in a way that isn't...obvious? I don't even know what kind of question I'm asking for an answer to here, but this doesn't seem right...

If I missed something while reading documentation, feel free to tell me to RTFM (again, this time with feeling) and close the issue with prejudice. If this is WAI but undocumented, I'll accept that and redesign my power network until it works in a way that pleases me. But if this is a bug, or sounds like a bug, I'm quite happy to work with you to see it fixed.

...and yeah, feel free to rename the title of this issue. I'd have put something more useful, but I have no idea what the h*ll's going on here.

Unrelated crash log attached so you can peruse the other mods loaded if you think it's a conflict, but honestly I think we're solid on compatibility, and it's not a rendering issue, so probably not OptiFine or anything... But just in case.

[crash-2018-06-25_15.20.21-client.txt](https://github.com/malte0811/IndustrialWires/files/2135451/crash-2018-06-25_15.20.21-client.txt)

**Comment by PegasusEpsilon** [comment]
Nevermind, I connected both full CESUs directly to the MFE (via wires) and they're still only moving 128EU/t total between the two of them. Confirmed that connecting both CESUs directly to the MFE without any wires pushes 128EU/t into the MFE *each*, for 256EU/t total.

This is the closest I can get to ideal output from 8 triple water wheels, and the absurd nonsense I have to resort to to get it to happen is just wrong.

[Flickr because Github doesn't like the file](https://farm2.staticflickr.com/1826/29141647028_3b658de1fc_o.png)

**Comment by malte0811** [comment]
So this only happens when you have more than one power source connected to the same output(s)? In that case this is a duplicate of #28. That issue should be fixed for the next build (I'm hoping to get it out sometime this week).

**Comment by PegasusEpsilon** [comment]
Looks likely. There seems to be many instances when this happens, but I'll wait for the next version before I file another bug report. Don't suppose you've got an alpha or something I could throw up on the server and see if the problem magically vanishes? I don't mind testing. This is driving me mad.

Another thing you might care to know about, though I don't mind it, if you place a relay on dirt, and then break the dirt, the relay stays. IE relays fall when the dirt block is broken, but not yours. Feel free to not fix this one, though. Floating relays make my wiring happy.

**Comment by malte0811** [comment]
If you know how to build mods, the version on the master branch of this repo should have the fix, as well as one for the floating relays (if you have a JDK installed it should be as easy as running `./gradlew build`).
Something I still need to fix for the next release is connectors blowing up on the (small) mechanical converters.

**Comment by PegasusEpsilon** [comment]
Or...

`\trizen -S jdk gradle`
`git clone ...`
`JAVA_HOME=/usr/lib/jvm/java-8-openjdk/ gradle build`

But yeah, I'll poke it and see if I can get it working. :)

**Comment by PegasusEpsilon** [comment]
Those numbers are much more sensible. Thanks for the help. :)
