### ISSUE TITLE
Issues when editing components

### ISSUE THREAD

**Issue by Milmaxleo** [malte0811/IndustrialWires#32]
Whenever I try to edit a component via the GUI, the game crashed upon closing or trying to change the GUI.

Crash report:https://hastebin.com/dabuyiquzu.sql

**Comment by malte0811** [comment]
cb7aef646a12c94e8a6550906c73cb72f710161c
Github had some issues earlier today, I assume that's why the commit didn't close this issue.

**Comment by Milmaxleo** [comment]
Sorry new to GitHub, but does that mean the issue was resolved?

**Comment by malte0811** [comment]
Yes, I even made a new release on CurseForge. Usually issues are closed automatically when I fix them in code, but that didn't work yesterday.
