### ISSUE TITLE
Missing Localisation for IW Mutliblock Names on Immersive Petroleum Projectors

### ISSUE THREAD

**Issue by TechnoMysterio** [malte0811/IndustrialWires#33]
Localisation is missing for the names of IW multiblock structures, specifically on the tooltips for Immersive Petroleum's projectors set to preview them. For instance, an IP projector set to show the Marx Generator:

![2018-07-16_20 58 21](https://user-images.githubusercontent.com/5113920/42780430-0c179dcc-893b-11e8-836f-a6511dc58d77.png)

**Comment by malte0811** [comment]
I'll fix this in the next release, which won't happen for a few weeks at least unless some major issue gets reported. There are a couple of other issues with the IP projectors and my multiblocks, see Flaxbeard/ImmersivePetroleum#119. I can't fix those unless Flaxbeard changes thing in IP.

**Comment by malte0811** [comment]
Sorry, hit the wrong button.
