### ISSUE TITLE
Conflict with immersive petroleum?

### ISSUE THREAD

**Issue by wormzjl** [malte0811/IndustrialWires#34]
I tried to make a distillation tower from immersive petroleum on a server, but when forming structures it become something weird from Industrial wires:
![image](https://user-images.githubusercontent.com/2989009/42838473-378e0ad8-8a01-11e8-977c-ea5df1fa9c74.png)
If one tries to break it, the server crashes
https://gist.github.com/wormzjl/242e78990bca4d6e8750d80387604986

**Comment by wormzjl** [comment]
Could be related to https://github.com/malte0811/IndustrialWires/issues/30

**Comment by malte0811** [comment]
I'll fix the crash, the structure conflict is something I'll need to talk to @Flaxbeard about.
