### ISSUE TITLE
 MultiBlock Rendering issues with other mods

### ISSUE THREAD

**Issue by ghost** [malte0811/IndustrialWires#44]
versions
  IE:any
  IW:any that has the mechanical multiblock
  optifine:HD_U_E2
  minecraft:1.12.2

the problem is that with optifine installed the electrodes dont render correctly.

**Comment by ghost** [comment]
i tried it in my moddpack without optifine and it still breaks the rendering .
optifine on its own breaks it but some other mod seems to break it to

**Comment by raindropworks** [comment]
I don't have Optifine (I have FoamFix) and I noticed the same thing with copper and gold connectors.  I'm not sure if it might be because I don't have IC2 or GT installed (so nothing that makes an EU energy-net

**Comment by ghost** [comment]
ill try it with ic2

**Comment by ghost** [comment]
the rendering still doesnt work

**Comment by malte0811** [comment]
The connector render issue is easy, I forgot to remove one check when I made the connectors work without IC2 (the one for registering the models). The OF issue is something completely different, I'll try to get that fixed but can't promise anything.
