### ISSUE TITLE
Marx not processing/destroying ore blocks

### ISSUE THREAD

**Issue by 1234Eldo** [malte0811/IndustrialWires#47]
Marx Generator is successfully built/formed and powered.  Successfully built control panel and configured exactly as the manual and your tutorial.  Panel is an exact clone of your tutorial, is fully functional, and both top and bottom coils independently indicate the dial setting once fully charged. Generator will successfully empty test fire, and will kill mobs and players, but will not destroy ores of any type regardless of settings.  The "spark" simply passes directly through placed blocks, then the machine re-charges.  Tried the "Discharge Meter" block with an aluminum wire as shown in your video, but the wire will not "burn" upon discharge, and the "meter block" displays nothing, as if it were still freshly placed.  I have stripped Minecraft down to only IC2, IE, and Industrial Wires; absolute bare minimum to get "Wires" to run.   Any suggestions?

Minecraft 1.12.2

Forge 2768

Java 1.8.0_191

IC2, IE, and Ind. Wires: Latest releases possible on CurseForge as of 11/18/2018.

**Comment by malte0811** [comment]
Fixed, thanks for the report. I'll probably release a build with the fix in a couple of days.

**Comment by 1234Eldo** [comment]
fantastic, tyvm.  I had been fighting with it for a long time, assumed it was something I was doing wrong or a mod conflict.  Was very hesitant to ask a question or report a bug until was 100% sure it wasn't me.  Hope it was something easy.  Thanks for the mod very much and your willingness to support it.
