### ISSUE TITLE
Marx generator can't charge up

### ISSUE THREAD

**Issue by malter179** [malte0811/IndustrialWires#48]
The power cannot go up more than a little bit before the 5 on the panel.
![2018-12-02_19 29 15](https://user-images.githubusercontent.com/45540744/49343408-0a52d600-f669-11e8-9887-bebc5509fe02.png)

Solution;The problem was that it was an old version of the mod.

**Comment by malter179** [comment]
I've tried plugging it op on multiple generators, and even creative capacitors, but it still won't work.

**Comment by malte0811** [comment]
What version of IW are you using? What version of IE? I used the Marx just a few hours ago with the latest versions of IE and IW, worked just fine. You could try using IE wires rather than the "universal" ones, the IE ones definitely work.
Unrelated, but you may be able to answer this: Why are people using IW all the sudden? There's been a very noticeable increase in comments etc over the last couple of weeks.

**Comment by malter179** [comment]
I am using IE power, nothing from the other ones. And for your question, I like it because of the control panels, and the Marx generator seems cool, so that's what might draw people to it.
IE version - 0.12-84 and
IW version - 1.7-28

**Comment by malte0811** [comment]
Both of those versions are quite old, could you try updating to IE 0.12-86 and IW 1.7-33 (released just a few hours ago)?

**Comment by 1234Eldo** [comment]
Unsure on everyone else, as I play 99% SP (or with my kids LAN), but IW is an awesome complimentary mod to the rest of the IE family and IC2.  Perhaps the long wait for mod-ed 1.13 is causing people to try other/new options.  IE (and it's wonderful companions) along with IC2 ALWAYS make up the core of EVERY mod set I ever play, and will continue to be such for as long as they are supported.

**Comment by malter179** [comment]
I'll try. Didn't play minecraft in a long time, so I didn't update any mods. I'll update it now, and I will write the (hopefully good) results here.

**Comment by malter179** [comment]
I updated the mods, but now the game window closes somewhere in the second stage while loading the mods. But the javaw process is still on in the task manager. I'll try to see if something is incompatible, now that I downloaded the new mods and forge version, tomorrow, i'm too sleepy and worked out at the moment.

**Comment by malte0811** [comment]
I made a mistake when uploading build 33, there's a new version of it on CF now that shouldn't crash on startup.

**Comment by malter179** [comment]
Now, instead of the game menu opening up after the loading, it crashes. Log:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  FMLPlugin (elulib-0.1.12.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-86.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 12/3/18 4:42 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Not Enough Items (nei)
Caused by: java.lang.IllegalAccessError: tried to access class net.minecraft.potion.PotionHelper$MixPredicate from class codechicken.nei.util.helper.potion.PotionRecipeHelper
	at codechicken.nei.util.helper.potion.PotionRecipeHelper.init(PotionRecipeHelper.java:61)
	at codechicken.nei.init.NEIInitialization.bootNEI(NEIInitialization.java:67)
	at codechicken.nei.proxy.ProxyClient.loadComplete(ProxyClient.java:54)
	at codechicken.nei.NotEnoughItems.loadComplete(NotEnoughItems.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:752)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_144, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 995099672 bytes (949 MB) / 2746744832 bytes (2619 MB) up to 3340763136 bytes (3186 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3584m -XX:MaxPermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_E1 48 mods loaded, 48 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State   | ID                   | Version          | Source                                            | Signature                                |
	|:------- |:-------------------- |:---------------- |:------------------------------------------------- |:---------------------------------------- |
	| UCHIJA  | minecraft            | 1.12.2           | minecraft.jar                                     | None                                     |
	| UCHIJA  | mcp                  | 9.42             | minecraft.jar                                     | None                                     |
	| UCHIJA  | FML                  | 8.0.99.99        | modpack.jar                                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA  | forge                | 14.23.5.2768     | modpack.jar                                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA  | openmodscore         | 0.11.5           | minecraft.jar                                     | None                                     |
	| UCHIJA  | opencomputers|core   | 1.7.2.67         | minecraft.jar                                     | None                                     |
	| UCHIJA  | elucore              | 1.0              | minecraft.jar                                     | None                                     |
	| UCHIJA  | jei                  | 4.11.0.202       | jei_1.12.2-4.11.0.202.jar                         | None                                     |
	| UCHIJA  | mantle               | 1.12-1.3.2.24    | Mantle-1.12-1.3.2.24.jar                          | None                                     |
	| UCHIJA  | tconstruct           | 1.12.2-2.10.1.87 | TConstruct-1.12.2-2.10.1.87.jar                   | None                                     |
	| UCHIJA  | immersiveengineering | 0.12-86          | ImmersiveEngineering-0.12-86.jar                  | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCHIJA  | alternatingflux      | 0.12-4           | alternatingflux-0.12-4.jar                        | None                                     |
	| UCHIJA  | bibliocraft          | 2.4.5            | BiblioCraft[v2.4.5][MC1.12.2].jar                 | None                                     |
	| UCHIJA  | biomesoplenty        | 7.0.1.2384       | BiomesOPlenty-1.12.2-7.0.1.2384-universal.jar     | None                                     |
	| UCHIJA  | blockcraftery        | 0.1.3            | blockcraftery-0.1.3.jar                           | None                                     |
	| UCHIJA  | ceramics             | 1.12-1.3.4       | Ceramics-1.12-1.3.4.jar                           | None                                     |
	| UCHIJA  | codechickenlib       | 3.1.5.331        | CodeChickenLib-1.12.2-3.1.5.331-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA  | cutehamstermod       | 1.1              | cutehamstermod-1.1.jar                            | ac38a3286ab9f4777b0023f0f6280caa9369d575 |
	| UCHIJA  | cyberware            | 0.2.10.12        | cyberware-1.12.2-0.2.10.12.jar                    | 67a0e286dc0d4b502f3c92ac20b953517b52d0a9 |
	| UCHIJA  | earthworks           | 1.3.4.3          | Earthworks-1.12-1.3.6.jar                         | None                                     |
	| UCHIJA  | engineersdoors       | 0.7.2            | engineersdoors-0.7.2.jar                          | None                                     |
	| UCHIJA  | flansmod             | 5.5.2            | Flan's Mod-1.12.2-5.5.2.jar                       | None                                     |
	| UCHIJA  | flansmodapocalypse   | 1.0              | Flan's Mod-1.12.2-5.5.2.jar                       | None                                     |
	| UCHIJA  | cfm                  | 5.2.0            | furniture-5.2.0-1.12.2.jar                        | None                                     |
	| UCHIJA  | icbmclassic          | 1.12.2-3.0.0.29  | ICBM-classic-1.12.2-3.0.0b29.jar                  | None                                     |
	| UCHIJA  | immersivepetroleum   | 1.1.9            | immersivepetroleum-1.12.2-1.1.9.jar               | None                                     |
	| UCHIJA  | trackapi             | 1.1              | TrackAPI-1.1_1.12.jar                             | None                                     |
	| UCHIJA  | immersiverailroading | 1.3.1            | ImmersiveRailroading-1.3.1_1.12.jar               | None                                     |
	| UCHIJA  | immersivetech        | 1.3.10           | immersivetech-1.12-1.3.10.jar                     | None                                     |
	| UCHIJA  | ic2                  | 2.8.73-ex112     | industrialcraft-2-2.8.73-ex112.jar                | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJA  | landlust             | 1.12.2-0.3.6     | landlust-1.12.2-0.3.6.jar                         | None                                     |
	| UCHIJA  | malisiscore          | 1.12.2-6.4.0     | malisiscore-1.12.2-6.4.0.jar                      | None                                     |
	| UCHIJA  | malisisblocks        | 1.12.2-6.1.0     | malisisblocks-1.12.2-6.1.0.jar                    | None                                     |
	| UCHIJA  | malisisdoors         | 1.12.2-7.3.0     | malisisdoors-1.12.2-7.3.0.jar                     | None                                     |
	| UCHIJA  | malisisswitches      | 1.12.2-5.1.0     | malisisswitches-1.12.2-5.1.0.jar                  | None                                     |
	| UCHIJEE | nei                  | 2.4.1            | NotEnoughItems-1.12.2-2.4.1.233-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJ   | openmods             | 0.11.5           | OpenModsLib-1.12.2-0.11.5.jar                     | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UCHIJ   | openblocks           | 1.7.6            | OpenBlocks-1.12.2-1.7.6.jar                       | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UCHIJ   | opencomputers        | 1.7.2.67         | OpenComputers-MC1.12.2-1.7.2.67.jar               | None                                     |
	| UCHIJ   | harvestcraft         | 1.12.2u          | Pam's+HarvestCraft+1.12.2u.jar                    | None                                     |
	| UCHIJ   | pneumaticcraft       | 1.12.2-0.7.3-239 | pneumaticcraft-repressurized-1.12.2-0.7.3-239.jar | None                                     |
	| UCHIJ   | revolution           | 1.3              | revolution-1.3.jar                                | None                                     |
	| UCHIJ   | rustic               | 1.0.6            | rustic-1.0.6.jar                                  | None                                     |
	| UCHIJ   | worldedit            | 6.1.8            | worldedit-forge-mc1.12-6.1.8-dist.jar             | None                                     |
	| UCHIJ   | industrialwires      | 1.7-33           | IndustrialWires-1.7-33.jar                        | 7e11c175d1e24007afec7498a1616bef0000027d |
	| UCHIJ   | shetiphiancore       | 3.5.7            | shetiphiancore-1.12.0-3.5.7.jar                   | None                                     |
	| UCHIJ   | elulib               | 0.1.12           | elulib-0.1.12.jar                                 | None                                     |
	| UCHIJ   | justthetips          | 1.12-1.0.1.1     | justthetips-1.12-1.0.1.1.jar                      | None                                     |

	Loaded coremods (and transformers): 
MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  shetiphian.asm.ClassTransformer
FMLPlugin (elulib-0.1.12.jar)
  elucent.elulib.asm.ASMTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-86.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  openmods.core.OpenModsClassTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  li.cil.oc.common.asm.ClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.3.12618 Compatibility Profile Context 13.251.0.0' Renderer: 'AMD Radeon HD 6670'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	OptiFine Version: OptiFine_1.12.2_HD_U_E1
	OptiFine Build: 20180628-111228
	Render Distance Chunks: 6
	Mipmaps: 1
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.3.12618 Compatibility Profile Context 13.251.0.0
	OpenGlRenderer: AMD Radeon HD 6670
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 2

**Comment by malte0811** [comment]
Update NEI as well. There was a Forge update recently that broke most mods that dealt with potions in any way.

**Comment by malter179** [comment]
Just noticed that a minute ago. Minecraft is booting up right now, with the mods updated. Yet to check if there are any more problems, I hope not.

**Comment by malter179** [comment]
Game works, and Marx generator works perfectly! Would you just mind answering, how to create tilted control panels, like the one in the video for the generator?

**Comment by malte0811** [comment]
That's good to hear! It should say somewhere in the manual (unless I forgot to add it, which is quite possible), but you can create tilted control panels by placing the unfinished control panel in the engineer's workbench and adjusting the sliders (there's one for height and one for angle). The unfinished panel can be placed down as well, which should make finding a good angle and height easier.

**Comment by malter179** [comment]
> 
> 
> you can create tilted control panels by placing the unfinished control panel in the engineer's workbench

I should have thought of that! And thanks for the help!
