### ISSUE TITLE
Uninsulated ic2 wire gives insulated IW wire

### ISSUE THREAD

**Issue by wormzjl** [malte0811/IndustrialWires#64]
![image](https://user-images.githubusercontent.com/2989009/51078963-d387cb00-16be-11e9-9612-e7793fbe8f57.png)
Also is there anyway you can make the recipe appear in JEI?

**Comment by anar4732** [comment]
yeah, it's a bug, but it's not bad. it helped me make a lot of rubber :smile:

**Comment by wormzjl** [comment]
So there is also a dupe bug involved
