### ISSUE TITLE
Make mechanical multiblock decay rate configurable

### ISSUE THREAD

**Issue by Hawk777** [malte0811/IndustrialWires#92]
The current mechanical multiblock decay rate of 5% is far too high for my liking—I want to use them for energy storage because I like the concept and the appearance, but at 5% loss, it’s just not practical; once you store a decent amount of energy in flywheels, it just takes too much power to counteract the loss, so I’ve used capacitor banks instead. It would be nice if the loss rate were set in the config file rather than fixed in the source code, so different people with different play styles and different modpacks could rebalance the loss rate for their own preferences.

**Comment by malte0811** [comment]
I've stopped working on Industrial Wires (and should probably mark the repo as archived…), but you may be interested in the fork @Silfryi has been working on: [CurseForge](https://www.curseforge.com/minecraft/mc-mods/industrial-wires-reengineered)/[Github](https://github.com/Silfryi/IndustrialWires).
